project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_cleaning.qmd
        text: "Data Cleaning & Exploration"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd/ipynb
        text: "ML Methods"
      - href: nlp_methods.qmd/ipynb
        text: "NLP Methods"
format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true


